image: quay.io/openshift-community-operators/vault-config-operator@sha256:190eb3501816959c71e4b9d6689e277cfceece43010ededd1caeffc72df766b7
name: vault-config-operator.v0.1.1
package: vault-config-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: AuthEngineMount
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: PasswordPolicy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: Policy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: RandomSecret
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: SecretEngineMount
      version: v1alpha1
  - type: olm.package
    value:
      packageName: vault-config-operator
      version: 0.1.1
relatedImages:
  - image: quay.io/openshift-community-operators/vault-config-operator@sha256:190eb3501816959c71e4b9d6689e277cfceece43010ededd1caeffc72df766b7
    name: ""
  - image: quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47
    name: ""
  - image: quay.io/redhat-cop/vault-config-operator@sha256:1ec09955506a881011add9b23f518ab7217650bd09f971f7b593688cecb1d795
    name: ""
schema: olm.bundle
