image: quay.io/openshift-community-operators/vault-config-operator@sha256:e7d44f98892a16040a735a96e85b959d35d25164860b8a401c854a1e02d2d451
name: vault-config-operator.v0.1.0
package: vault-config-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: AuthEngineMount
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: PasswordPolicy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: Policy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: RandomSecret
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: SecretEngineMount
      version: v1alpha1
  - type: olm.package
    value:
      packageName: vault-config-operator
      version: 0.1.0
relatedImages:
  - image: quay.io/openshift-community-operators/vault-config-operator@sha256:e7d44f98892a16040a735a96e85b959d35d25164860b8a401c854a1e02d2d451
    name: ""
  - image: quay.io/redhat-cop/kube-rbac-proxy@sha256:fda7f669f6f5e0722c88946075f323681344a7639a77acae79fabc26eb5ad636
    name: ""
  - image: quay.io/redhat-cop/vault-config-operator@sha256:5ce02b001726dc749b6b543ccd43107d0a5f63dbd1e4a8c1a60ea3349cdecbb5
    name: ""
schema: olm.bundle
