image: quay.io/openshift-community-operators/ack-applicationautoscaling-controller@sha256:1d9f3693e30d325fb4e92db22cb1f3097d06450a09e93121ad8a5c14fafcb549
name: ack-applicationautoscaling-controller.v0.2.7
package: ack-applicationautoscaling-controller
properties:
  - type: olm.gvk
    value:
      group: applicationautoscaling.services.k8s.aws
      kind: ScalableTarget
      version: v1alpha1
  - type: olm.gvk
    value:
      group: applicationautoscaling.services.k8s.aws
      kind: ScalingPolicy
      version: v1alpha1
  - type: olm.package
    value:
      packageName: ack-applicationautoscaling-controller
      version: 0.2.7
relatedImages:
  - image: public.ecr.aws/aws-controllers-k8s/applicationautoscaling-controller:v0.2.7
    name: ""
  - image: quay.io/openshift-community-operators/ack-applicationautoscaling-controller@sha256:1d9f3693e30d325fb4e92db22cb1f3097d06450a09e93121ad8a5c14fafcb549
    name: ""
schema: olm.bundle
