image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:c305df4d650d14823612c6608b348c27f3772a5b2f679f9d1e402e4b8e71824c
name: namespace-configuration-operator.v1.1.0
package: namespace-configuration-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: GroupConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: NamespaceConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: UserConfig
      version: v1alpha1
  - type: olm.package
    value:
      packageName: namespace-configuration-operator
      version: 1.1.0
relatedImages:
  - image: quay.io/coreos/kube-rbac-proxy@sha256:e10d1d982dd653db74ca87a1d1ad017bc5ef1aeb651bdea089debf16485b080b
    name: ""
  - image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:c305df4d650d14823612c6608b348c27f3772a5b2f679f9d1e402e4b8e71824c
    name: ""
  - image: quay.io/redhat-cop/namespace-configuration-operator@sha256:17c9625eca7d476c62f2722973e84835f4279348253ba2ce8b790aabdab3c85d
    name: ""
schema: olm.bundle
