image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:d8c0c78842c5a1453959a02ae7f2363dfec4d7e01414a7feb7f692ed79e9d7eb
name: namespace-configuration-operator.v1.0.7
package: namespace-configuration-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: GroupConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: NamespaceConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: UserConfig
      version: v1alpha1
  - type: olm.package
    value:
      packageName: namespace-configuration-operator
      version: 1.0.7
relatedImages:
  - image: quay.io/coreos/kube-rbac-proxy:v0.5.0
    name: ""
  - image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:d8c0c78842c5a1453959a02ae7f2363dfec4d7e01414a7feb7f692ed79e9d7eb
    name: ""
  - image: quay.io/redhat-cop/namespace-configuration-operator:v1.0.7
    name: ""
schema: olm.bundle
