image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:384591ac16768a194fc667ed3e0babdd9b849ba2d64014700fa19854376c4f54
name: namespace-configuration-operator.v1.2.0
package: namespace-configuration-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: GroupConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: NamespaceConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: UserConfig
      version: v1alpha1
  - type: olm.package
    value:
      packageName: namespace-configuration-operator
      version: 1.2.0
relatedImages:
  - image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:384591ac16768a194fc667ed3e0babdd9b849ba2d64014700fa19854376c4f54
    name: ""
  - image: quay.io/redhat-cop/namespace-configuration-operator@sha256:4a95826bf31bce14603c8c5657a4a2264f24817de31807c6c7403780c8912105
    name: ""
  - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:6d57bfd91fac9b68eb72d27226bc297472ceb136c996628b845ecc54a48b31cb
    name: ""
schema: olm.bundle
