image: quay.io/openshift-community-operators/vault-config-operator@sha256:cdea4221d58cd884ba73c8688de56cba91f4fa370bb19d88d48b08217e6d7298
name: vault-config-operator.v0.2.0
package: vault-config-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: AuthEngineMount
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: GitHubSecretEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: GitHubSecretEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: PasswordPolicy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: Policy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: RabbitMQSecretEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: RabbitMQSecretEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: RandomSecret
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: SecretEngineMount
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: VaultSecret
      version: v1alpha1
  - type: olm.package
    value:
      packageName: vault-config-operator
      version: 0.2.0
relatedImages:
  - image: quay.io/openshift-community-operators/vault-config-operator@sha256:cdea4221d58cd884ba73c8688de56cba91f4fa370bb19d88d48b08217e6d7298
    name: ""
  - image: quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47
    name: ""
  - image: quay.io/redhat-cop/vault-config-operator@sha256:31c50bc2a1b24a66a0d60a778dea6f00b44922e7de2a91a79d08a81087092904
    name: ""
schema: olm.bundle
