image: quay.io/openshift-community-operators/vault-config-operator@sha256:ae37cf4e49f5828db3fa15460b3efcb2e373d65e2bad7d24da306fcbaa600928
name: vault-config-operator.v0.1.2
package: vault-config-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: AuthEngineMount
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: DatabaseSecretEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: KubernetesAuthEngineRole
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: PasswordPolicy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: Policy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: RandomSecret
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: SecretEngineMount
      version: v1alpha1
  - type: olm.package
    value:
      packageName: vault-config-operator
      version: 0.1.2
relatedImages:
  - image: quay.io/openshift-community-operators/vault-config-operator@sha256:ae37cf4e49f5828db3fa15460b3efcb2e373d65e2bad7d24da306fcbaa600928
    name: ""
  - image: quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47
    name: ""
  - image: quay.io/redhat-cop/vault-config-operator@sha256:7f498e11fdd8558c70358e933fb3b469ff3d45c8a933547c3db1f9364a4f2b07
    name: ""
schema: olm.bundle
