image: quay.io/openshift-community-operators/flux@sha256:dc7fb5046d00ad4b81cfe52975c4d73645f916920b8279a1fd02c5db7bea463d
name: flux.v0.14.2
package: flux
properties:
  - type: olm.gvk
    value:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      version: v2beta1
  - type: olm.gvk
    value:
      group: image.toolkit.fluxcd.io
      kind: ImagePolicy
      version: v1alpha1
  - type: olm.gvk
    value:
      group: image.toolkit.fluxcd.io
      kind: ImagePolicy
      version: v1alpha2
  - type: olm.gvk
    value:
      group: image.toolkit.fluxcd.io
      kind: ImageRepository
      version: v1alpha1
  - type: olm.gvk
    value:
      group: image.toolkit.fluxcd.io
      kind: ImageRepository
      version: v1alpha2
  - type: olm.gvk
    value:
      group: image.toolkit.fluxcd.io
      kind: ImageUpdateAutomation
      version: v1alpha1
  - type: olm.gvk
    value:
      group: image.toolkit.fluxcd.io
      kind: ImageUpdateAutomation
      version: v1alpha2
  - type: olm.gvk
    value:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      version: v1beta1
  - type: olm.gvk
    value:
      group: notification.toolkit.fluxcd.io
      kind: Alert
      version: v1beta1
  - type: olm.gvk
    value:
      group: notification.toolkit.fluxcd.io
      kind: Provider
      version: v1beta1
  - type: olm.gvk
    value:
      group: notification.toolkit.fluxcd.io
      kind: Receiver
      version: v1beta1
  - type: olm.gvk
    value:
      group: source.toolkit.fluxcd.io
      kind: Bucket
      version: v1beta1
  - type: olm.gvk
    value:
      group: source.toolkit.fluxcd.io
      kind: GitRepository
      version: v1beta1
  - type: olm.gvk
    value:
      group: source.toolkit.fluxcd.io
      kind: HelmChart
      version: v1beta1
  - type: olm.gvk
    value:
      group: source.toolkit.fluxcd.io
      kind: HelmRepository
      version: v1beta1
  - type: olm.package
    value:
      packageName: flux
      version: 0.14.2
relatedImages:
  - image: ghcr.io/fluxcd/helm-controller:v0.10.1
    name: ""
  - image: ghcr.io/fluxcd/image-automation-controller:v0.11.0
    name: ""
  - image: ghcr.io/fluxcd/image-reflector-controller:v0.9.1
    name: ""
  - image: ghcr.io/fluxcd/kustomize-controller:v0.12.2
    name: ""
  - image: ghcr.io/fluxcd/notification-controller:v0.14.1
    name: ""
  - image: ghcr.io/fluxcd/source-controller:v0.13.2
    name: ""
  - image: quay.io/openshift-community-operators/flux@sha256:dc7fb5046d00ad4b81cfe52975c4d73645f916920b8279a1fd02c5db7bea463d
    name: ""
schema: olm.bundle
