image: quay.io/openshift-community-operators/ack-applicationautoscaling-controller@sha256:6907c03c33f568f6197952ab253a0ab704cf3711ebb151a6448d17c6702ab36c
name: ack-applicationautoscaling-controller.v0.2.3
package: ack-applicationautoscaling-controller
properties:
  - type: olm.gvk
    value:
      group: applicationautoscaling.services.k8s.aws
      kind: ScalableTarget
      version: v1alpha1
  - type: olm.gvk
    value:
      group: applicationautoscaling.services.k8s.aws
      kind: ScalingPolicy
      version: v1alpha1
  - type: olm.package
    value:
      packageName: ack-applicationautoscaling-controller
      version: 0.2.3
relatedImages:
  - image: public.ecr.aws/aws-controllers-k8s/applicationautoscaling-controller:v0.2.3
    name: ""
  - image: quay.io/openshift-community-operators/ack-applicationautoscaling-controller@sha256:6907c03c33f568f6197952ab253a0ab704cf3711ebb151a6448d17c6702ab36c
    name: ""
schema: olm.bundle
