image: quay.io/openshift-community-operators/ack-applicationautoscaling-controller@sha256:e95ceebbb45f9d92331e4637a53129126f79ad53067afb78b1c927cf2d1c6fad
name: ack-applicationautoscaling-controller.v0.2.8
package: ack-applicationautoscaling-controller
properties:
  - type: olm.gvk
    value:
      group: applicationautoscaling.services.k8s.aws
      kind: ScalableTarget
      version: v1alpha1
  - type: olm.gvk
    value:
      group: applicationautoscaling.services.k8s.aws
      kind: ScalingPolicy
      version: v1alpha1
  - type: olm.package
    value:
      packageName: ack-applicationautoscaling-controller
      version: 0.2.8
relatedImages:
  - image: public.ecr.aws/aws-controllers-k8s/applicationautoscaling-controller:v0.2.8
    name: ""
  - image: quay.io/openshift-community-operators/ack-applicationautoscaling-controller@sha256:e95ceebbb45f9d92331e4637a53129126f79ad53067afb78b1c927cf2d1c6fad
    name: ""
schema: olm.bundle
