defaultChannel: stable
icon:
  base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzNy44MyA0MC42Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6IzAxMDEwMTt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlByaXNtYS1jbG91ZC1ibGFjazwvdGl0bGU+PHBvbHlnb24gY2xhc3M9ImNscy0xIiBwb2ludHM9IjIwLjMgMjcuMDcgMjAuMyA4LjI3IDMwLjEyIDI3LjA3IDIwLjMgMjcuMDciLz48cG9seWdvbiBjbGFzcz0iY2xzLTEiIHBvaW50cz0iMjAuMyA4LjI3IDEwLjQ4IDI3LjA3IDIwLjMgMjcuMDcgMjAuMyA0MC42IDAgMjAuMyAxMC4zOCA5LjkyIDEyLjAzIDguMjcgMjAuMyAwIDIwLjMgOC4yNyIvPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTM3LjgzLDI3LjA3YTYuMDYsNi4wNiwwLDEsMSwwLTEyLjExdjIuNGEzLjY1LDMuNjUsMCwxLDAsMCw3LjNaIi8+PC9zdmc+
  mediatype: image/svg+xml
name: pcc-operator
schema: olm.package
