image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:8e5270d8879e6bd8bb9b95bb950a110b3f1ac82b353f9ec221c318f33b569a7f
name: namespace-configuration-operator.v1.2.1
package: namespace-configuration-operator
properties:
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: GroupConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: NamespaceConfig
      version: v1alpha1
  - type: olm.gvk
    value:
      group: redhatcop.redhat.io
      kind: UserConfig
      version: v1alpha1
  - type: olm.package
    value:
      packageName: namespace-configuration-operator
      version: 1.2.1
relatedImages:
  - image: quay.io/openshift-community-operators/namespace-configuration-operator@sha256:8e5270d8879e6bd8bb9b95bb950a110b3f1ac82b353f9ec221c318f33b569a7f
    name: ""
  - image: quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47
    name: ""
  - image: quay.io/redhat-cop/namespace-configuration-operator@sha256:1285780fb8e25852ba6317c76df8d1d9cc08507d08766598ab6c06e0a84394c3
    name: ""
schema: olm.bundle
